### PR TITLE
Use deployed .pom instead of jar bundled pom.xml for dependency resolution

### LINKED ISSUE #29: Support jars lacking a pom.xml
Fix https://github.com/cljdoc/cljdoc/issues/404

This should be possible by using the maven resolver to get the dependency list and merging it at the top level.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
Fix #29

In draft to collect feedback on approach, a few thoughts that come to
mind:

* Using src/main/clojure relies on a detail in tools.deps.alpha that
this is a path used for resolution.  I don't think this will ever go
away though, and it's somewhat part of the API due to it's position.
This is certainly "complected".
* A good dependency to test this with would be `{:project "miikka/clj-branca", :version "0.1.0", :jarpath "https://repo.clojars.org/miikka/clj-branca/0.1.0/clj-branca-0.1.0.jar", :pompath "https://repo.clojars.org/miikka/clj-branca/0.1.0/clj-branca-0.1.0.pom", :repos {"clojars" {:url "https://repo.clojars.org/"}, "central" {:url "https://repo.maven.apache.org/maven2/"}}}`
* There's a few docs which should be updated before this can be merged

### CODE REVIEW

**Comment by lread** [comment]
Thanks for working on this @SevereOverfl0w!  I humbly accept your review request. 🙂 

**Tools deps detail**
> Using src/main/clojure relies on a detail in tools.deps.alpha that
> this is a path used for resolution.

I think your docstring explains the detail?
> dir will be relative to target-dir in a way suitable for use with a pom.xml as a local root

Should we pester Alex in tools-deps channel on Slack to see what he thinks of relying on this?

**Impacts?**
I'm trying to think of any potential issues but am not coming up with much.

1. Who does this change benefit? How many tools do not bundle a `pom.xml`? Was it juxt/pack that did not?
1. If someone takes the no bundled `pom.xml` approach, will it be likely that their scm is configured appropriately?  
1. I'm guessing that if there is a bundled `pom.xml`, it will always be an exact copy of the maven repo `.pom`?

**Integration test**
Should we add your `miikka/clj-branca` example to our integration tests?

**docs**
Agreed, we should update accordingly, but we can work on answering questions first.

**Comment by SevereOverfl0w** [comment]
> Should we pester Alex in tools-deps channel on Slack to see what he thinks of relying on this?

I chased this, he saw no problem.  It makes sense as anyone who currently relies on it from an application perspective would otherwise be broken.  We always have the fallback of modifying the pom.xml ourselves, but I'm avoiding that for laziness/sanity reasons right now - doing xml transforms seems a bit eh for no real benefit.

> Who does this change benefit? How many tools do not bundle a pom.xml? Was it juxt/pack that did not?

I definitely don't have a measure, but anyone following the guide I wrote on bundling libs with pack will run into this, certainly.  Afaik, it's not a requirement to include the pom.xml in the jar.  This change means we'll be equally as reliable as Maven is when fetching deps.  I have no idea which accident of history resulted in it happening, seems odd to me even today!

> If someone takes the no bundled pom.xml approach, will it be likely that their scm is configured appropriately?

I don't think these two things are necessarily related, but it is certainly possible.  Although I've been thinking that it would be nice to be functional without SCM anyway, but I haven't even started looking at that.  But the code is right there, so it seems logical to me.

> I'm guessing that if there is a bundled pom.xml, it will always be an exact copy of the maven repo .pom?

It should be, if it isn't, someone is up to something.

>  Should we add your miikka/clj-branca example to our integration tests?

Yes, definitely.  I'll do that now :)

**Comment by SevereOverfl0w** [comment]
Added the tests!

**Comment by lread** [comment]
Thanks for following up @SevereOverfl0w, much appreciated!

Now that you've helped me to understand, I think I see your point now:  
- If the deployed `.pom` is the same as the jar bundled `pom.xml`
- and we are always working from a deployed artifact
- then why not use the deployed `.pom`
- to remove the requirement of folks having to bundle `pom.xml` in their jars

Is that right?

I think this makes sense, if @martinklepsch sees no issues either then I think we are good to go!

**Comment by SevereOverfl0w** [comment]
Yeah, exactly what I'm saying. There's also the added dimension of the downloaded pom.xml being the golden copy that, e.g. is used by maven when fetching dependencies.

**Comment by lread** [comment]
Should we update this PR title from "Use downloaded pom.xml for dependency resolution" to:
"Use deployed .pom instead of jar bundled pom.xml for dependency resolution"?

**Comment by martinklepsch** [comment]
I've been a little hesitant about this because I remembered that we support pointing the analyzer at a jar in which case the analyzer will resolve deps based on the included `META-INF/pom.xml`. This use case isn't really documented or recommended anywhere though it seems and so I'm fine with making things rely on the "external" `.pom` file.

That said I do think packaging tools like `pack` should include `META-INF/pom.xml`. Maven does this and so who knows what else might rely on it. And who doesn't like solving an unknown number of potential problems by copying a single file? 😹

**Comment by SevereOverfl0w** [comment]
@martinklepsch what's the process for pointing at a jar?  It might be trivial to support that.

**Comment by lread** [comment]
I am foggy on what is currently supported so I looked at the code.  

It seems that there is currently an assert on pompath:
https://github.com/cljdoc/cljdoc-analyzer/blob/0bb0e32e7f48c7654ce9f9446c3480eb6781396a/src/cljdoc_analyzer/runner.clj#L200-L213

Which means that the current cljdoc analyzer doesn't support working from the jar alone. It might have once, and could one day again, but doesn't today.

I did a quick google on the subject of not bundling the `pom.xml` in the jar and found the [following on stackoverflow](https://stackoverflow.com/questions/1677994/what-is-the-significance-of-the-pom-file-that-maven-places-in-a-jar-file-is-it). It seems the downside is the jar would not be self-describing.  This is not an issue for cljdoc itself as it currently does not necessarily have to rely on self-describing jars (well at least after this PR it would not).

My personal, and perhaps naive, opinion is that while it seems like a good practice to bundle the `pom.xml` in the jar,  I currently see no technical reason for cljdoc to  enforce this practice.

**Comment by martinklepsch** [comment]
> Which means that the current cljdoc analyzer doesn't support working from the jar alone. It might have once, and could one day again, but doesn't today.

Maybe it never did and I'm just misremembering, I'm ok moving forward without explicitly supporting jar-only analysis. 

> My personal, and perhaps naive, opinion is that while it seems like a good practice to bundle the pom.xml in the jar, I currently see no technical reason for cljdoc to enforce this practice.

Same. 👍 

I'm ok merging this but I think we should document the point about `src/main/clojure` in the code as well, in particular why it is required.

**Comment by lread** [comment]
@SevereOverfl0w once you have handled @martinklepsch's request:

> I'm ok merging this but I think we should document the point about src/main/clojure in the code as well, in particular why it is required.

And if you still feel that supporting jars that don't include a `pom.xml` is important, feel free to merge to master and make live on cljdoc!

**Comment by SevereOverfl0w** [comment]
@martinklepsch just to make sure I understood, is this the change you would like?

```clojure
(defn- unpack-jar!
  "Returns dir where jar contents has been unpacked under `target-dir`.  dir
  will be relative to target-dir in a way suitable for use with a pom.xml as a
  local root."
  [local-jar-path target-dir]
  ;; If a pom is read from target-dir, src/main/clojure relative to that pom is
  ;; added to the classpath by tdeps.
  (let [jar-contents-dir (io/file target-dir "src/main/clojure")]
    (unzip! local-jar-path jar-contents-dir)
    (clean-jar-contents! jar-contents-dir)
    jar-contents-dir))
```

**Pull request merged**
