### PR TITLE
Fix empty namespaces

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
When a namespace is empty (no `(ns)` declaration), a namespace won't be
found in the state.  Instead of returning `{:publics ()}`, don't insert
the namespace at all for response.

There's 2 effects of this:
1. Empty namespaces won't show up anywhere
2. If the namespace fails to analyze due to warnings (e.g. in the case
of exoscale/coax:1.0.0-alpha4) then it won't show up silently. But
currently it just fails.

### CODE REVIEW

**Comment by martinklepsch** [comment]
> Empty namespaces won't show up anywhere

Would this mean a namespace that has a docstring but no vars would no longer be returned? Or when you say empty you mean proper empty, i.e. no metadata at all? 

Generally I'd like to improve error reporting instead of silently failing, at least initially. Maybe we could throw an error like

> This file doesn't look like a proper Clojure namespace: "pinkgorilla/controls/tabs.cljs"

What do you think?

**Comment by lread** [comment]
Related: https://github.com/cljdoc/cljdoc/issues/358. In this case the file had no ns declaration in it.  Which is similar to what you found @SevereOverfl0w, but in your case the file contained comments. 

Note that we did not make changes to cljdoc to handle this, after the author understood the problem, he got rid of the empty namespace.

At the time I was thinking a better error message would help.  But also thought if the builds are passing with these empty files, cljdoc should probably just handle them too.

**Comment by SevereOverfl0w** [comment]
This only refers to proper empty, no (ns) declaration.

**Comment by lread** [comment]
Yeah, the source problem is more of an empty file than an empty namespace.

**Comment by martinklepsch** [comment]
Could we print something whenever an empty namespace is deleted? I reckon this wouldn't happen very often and just want to make sure that it's super obvious when it happens to make debugging builds as easy as possible. 

@SevereOverfl0w I gave you push access to this repo (and invited you to the cljdoc org) so feel free to merge this PR when you think it's ready. We'll still need to update the cljdoc repo to use the new SHA [here](https://github.com/cljdoc/cljdoc/blob/2ab56f3dd0adf3176e10a762219e5654e3afda90/src/cljdoc/analysis/service.clj#L37-L38). If you want to deploy a fresh release, go for it. Otherwise I can do it too :)

**Comment by SevereOverfl0w** [comment]
Pondering this one.  If it wasn't for Coax I'd be less worried.  For some reason Coax totally fails to analyze, and that causes us to get no analysis for that either.  These two cases are indistinguishable.

I think it would be perfectly OK to reject this PR and say cljdoc doesn't support empty files, especially if we can't figure out how to distinguish empty & successful from failing.

I will investigate coax and see what's up there.  The warnings I got for it were _really_ weird.

**Comment by SevereOverfl0w** [comment]
@martinklepsch do you mean just something as simple as printing to stdout during the analysis in metagetta?

I figured out that coax was broken by enabling compiler warnings in the call the `analyze-file`, we could turn that on generally to help distinguish the cases.

**Comment by SevereOverfl0w** [comment]
Looks like coax is fixed by #24, which makes me less worried. @martinklepsch if you confirm how to warn, I can take care of that.  I'll also add a test against gorilla-ui & rebase this against master, as that makes sense now.

**Comment by martinklepsch** [comment]
> @martinklepsch do you mean just something as simple as printing to stdout during the analysis in metagetta?

Yes, just `println` is fine :+1: 

> Looks like coax is fixed by #24

Sweet! 

> I figured out that coax was broken by enabling compiler warnings in the call the analyze-file, we could turn that on generally to help distinguish the cases.

I'm not 100% sure what you mean here but if it helps with debugging builds, I'm for it 😄

**Comment by SevereOverfl0w** [comment]
Let's skip turning on warnings, because the errors it gave were really strange and they don't seem to have been related.

**Comment by SevereOverfl0w** [comment]
println added, commit message clarified with current state of understanding of the bug.  I can add a gorilla-ui test once #24 is merged.

**Pull request merged**
